# Generated by Django 5.2.5 on 2025-09-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_content_news_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_views',
            field=models.IntegerField(default=0),
        ),
    ]
