# Generated by Django 5.2.5 on 2025-09-30 18:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_news_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='news_views',
            new_name='product_views',
        ),
    ]
